# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20180206_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='urls',
            new_name='url',
        ),
    ]
